// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlRf5jKnJC_pQQEdFp3_e47cuIPGooPm8',
    appId: '1:386228429680:web:ae2020c10b2173ec3b25b5',
    messagingSenderId: '386228429680',
    projectId: 'spotify-69fe4',
    authDomain: 'spotify-69fe4.firebaseapp.com',
    storageBucket: 'spotify-69fe4.firebasestorage.app',
    measurementId: 'G-BK9WDCEYJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7DWWp8MU5SG9XE8vlLM1J-6Jhik0DpLQ',
    appId: '1:386228429680:android:89ba2c98f3305c663b25b5',
    messagingSenderId: '386228429680',
    projectId: 'spotify-69fe4',
    storageBucket: 'spotify-69fe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxf_-PWt94cwrGn5pV4fRZSWEZiHD7kWg',
    appId: '1:386228429680:ios:1f877f9e629657c93b25b5',
    messagingSenderId: '386228429680',
    projectId: 'spotify-69fe4',
    storageBucket: 'spotify-69fe4.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxf_-PWt94cwrGn5pV4fRZSWEZiHD7kWg',
    appId: '1:386228429680:ios:1f877f9e629657c93b25b5',
    messagingSenderId: '386228429680',
    projectId: 'spotify-69fe4',
    storageBucket: 'spotify-69fe4.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlRf5jKnJC_pQQEdFp3_e47cuIPGooPm8',
    appId: '1:386228429680:web:0ccabdeef10c75ab3b25b5',
    messagingSenderId: '386228429680',
    projectId: 'spotify-69fe4',
    authDomain: 'spotify-69fe4.firebaseapp.com',
    storageBucket: 'spotify-69fe4.firebasestorage.app',
    measurementId: 'G-7HFVLDXDSZ',
  );
}
